#!/usr/bin/env bash
set -euo pipefail

# setup_loaf.sh
# Usage: bash setup_loaf.sh
# Prompts user for loaf name, stats, and attacks. Creates a loaf folder with loaf.json,
# a Streamlit-compatible module at <NAME>/main.py, and a training script dql_agent_<NAME>.py
# (a copy of dql_agent.py with the name variable set and the random loaf line replaced
#  with a Loaf(...) instantiation matching the user's inputs).

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Validate loaf name (only letters, numbers, -, _)
prompt_loaf_name() {
  while true; do
    read -r -p "Enter a name for your loaf (letters, numbers, -, _ only): " LOAF_NAME
    if [[ -z "$LOAF_NAME" ]]; then
      echo "Name cannot be empty."
      continue
    fi
    if [[ "$LOAF_NAME" =~ ^[A-Za-z0-9_-]+$ ]]; then
      break
    else
      echo "Invalid characters. Use only letters, numbers, hyphen, or underscore."
    fi
  done
}

# Prompt for distributing 6 extra points
prompt_stats() {
  echo "You have 6 extra stat points to distribute across Flour, Salt, Sugar."
  while true; do
    read -r -p "Extra Flour (0-6): " FLOUR
    read -r -p "Extra Salt  (0-6): " SALT
    read -r -p "Extra Sugar (0-6): " SUGAR
    # Validate numeric
    if ! [[ "$FLOUR" =~ ^[0-9]+$ ]] || ! [[ "$SALT" =~ ^[0-9]+$ ]] || ! [[ "$SUGAR" =~ ^[0-9]+$ ]]; then
      echo "Please enter integers only."
      continue
    fi
    if (( FLOUR < 0 || FLOUR > 6 || SALT < 0 || SALT > 6 || SUGAR < 0 || SUGAR > 6 )); then
      echo "Each value must be between 0 and 6."
      continue
    fi
    SUM=$((FLOUR + SALT + SUGAR))
    if (( SUM != 6 )); then
      echo "The three numbers must sum to 6. Currently they sum to $SUM. Try again."
      continue
    fi
    break
  done
}

# Present attacks and let the user pick 1-3 unique attacks
prompt_attacks() {
  echo
  echo "Select 1 to 3 attacks by number (separated by spaces)."
  echo "Available attacks:"
  ATTACKS=(
    "CRUST_CRUSHER"
    "LEECH_LOAF"
    "SANDWICH_TRAP"
    "OVEN_SPRING"
    "SECOND_RISE"
    "INSTANT_YEAST"
    "GLUTEN_SURGE"
  )
  for i in "${!ATTACKS[@]}"; do
    idx=$((i+1))
    printf "  %d) %s\n" "$idx" "${ATTACKS[$i]}"
  done

  while true; do
    read -r -p "Enter choices (e.g. 1 4 7): " -a CHOICES
    # remove duplicates by building associative map
    declare -A seen=()
    valid=true
    selected=()
    for c in "${CHOICES[@]}"; do
      if ! [[ "$c" =~ ^[0-9]+$ ]]; then
        valid=false
        break
      fi
      if (( c < 1 || c > ${#ATTACKS[@]} )); then
        valid=false
        break
      fi
      if [[ -n "${seen[$c]:-}" ]]; then
        continue
      fi
      seen[$c]=1
      selected+=( "$c" )
    done
    if ! $valid; then
      echo "Invalid choice(s). Try again."
      continue
    fi
    if (( ${#selected[@]} < 1 || ${#selected[@]} > 3 )); then
      echo "Pick between 1 and 3 unique attacks."
      continue
    fi
    break
  done

  # Convert selected numbers to zero-based enum values
  ATTACK_VALUES=()
  for c in "${selected[@]}"; do
    val=$((c - 1))
    ATTACK_VALUES+=( "$val" )
  done
}

# Main
prompt_loaf_name
prompt_stats
prompt_attacks

LOAF_DIR="$REPO_ROOT/$LOAF_NAME"

if [[ -d "$LOAF_DIR" ]]; then
  echo "Directory '$LOAF_DIR' already exists."
  read -r -p "Overwrite existing loaf folder? (y/N): " yn
  case "$yn" in
    [Yy]* ) rm -rf "$LOAF_DIR";;
    * ) echo "Aborting."; exit 1;;
  esac
fi

mkdir -p "$LOAF_DIR"

# Create loaf.json (Loaf.serialize uses extras as flour/salt/sugar and "action space" list of ints)
LOAF_JSON_PATH="$LOAF_DIR/loaf.json"

# Build JSON array string for action space
ACTION_ARRAY="["
first=1
for v in "${ATTACK_VALUES[@]}"; do
  if [[ $first -eq 1 ]]; then
    ACTION_ARRAY+="$v"
    first=0
  else
    ACTION_ARRAY+=", $v"
  fi
done
ACTION_ARRAY+="]"

cat > "$LOAF_JSON_PATH" <<EOF
{
  "flour": $FLOUR,
  "salt": $SALT,
  "sugar": $SUGAR,
  "action_space": $ACTION_ARRAY
}
EOF

echo "Created $LOAF_JSON_PATH"

# Create a Streamlit-friendly module at <NAME>/main.py that agent_arena.py can import.
# The module will:
# - load loaf.json and construct a Loaf
# - load model.pt if present (and create a DQNetwork); otherwise agent() picks a random attack

MAIN_PY_PATH="$LOAF_DIR/main.py"
cat > "$MAIN_PY_PATH" <<'PYEOF'
from breadbrawl import Loaf
import json
from pathlib import Path
import random

# NOTE: This module is auto-generated by setup_loaf.sh. It provides two functions:
#   loaf() -> returns a breadbrawl.Loaf instance
#   agent(obs) -> returns an Attack (from loaf.action_space)
#
# If model.pt exists in the same folder, it will attempt to load a PyTorch model.
# If PyTorch is not available or model.pt is missing, the agent will act randomly.

NAME = "__LOAF_NAME__"

def _load_loaf():
    p = Path(f"{NAME}/loaf.json")
    with p.open("r") as f:
        data = json.load(f)
    return Loaf.deserialize(data)

your_loaf = _load_loaf()

# Lazy import/model loading so Streamlit can still run without torch if desired.
_model = None
try:
    import torch
    from dql_agent import DQNetwork
    model_path = Path(f"{NAME}/model.pt")
    if model_path.exists():
        _model = DQNetwork(your_loaf, 10, len(your_loaf.action_space))
        _model.load_state_dict(torch.load(model_path))
        _model.eval()
except Exception:
    # If torch isn't installed or model fails to load, fall back to random policy.
    _model = None

def loaf():
    return your_loaf

def agent(obs):
    # obs is the observation (vector) - DQNetwork.select_action expects the vector.
    if _model is None:
        return your_loaf.random_attack()
    try:
        return _model.select_action(obs)
    except Exception:
        return your_loaf.random_attack()
PYEOF

# Replace placeholder with actual loaf name
sed -i "s/__LOAF_NAME__/${LOAF_NAME}/g" "$MAIN_PY_PATH"
echo "Created $MAIN_PY_PATH"

# Create a training script dql_agent_<NAME>.py by copying dql_agent.py and replacing
# the 'name = ' line and replacing the random_loaf instantiation with a concrete Loaf(...)
if [[ ! -f "$REPO_ROOT/dql_agent.py" ]]; then
  echo "Warning: dql_agent.py not found at repo root. Training script will not be created."
else
  TRAIN_SCRIPT="$REPO_ROOT/dql_agent_${LOAF_NAME}.py"
  # Copy original and replace the first occurrence of a line starting with name =
  awk -v n="name = \"${LOAF_NAME}\"" 'BEGIN{replaced=0}
  {
    if(!replaced && $0 ~ /^name[[:space:]]*=/) {
      print n
      replaced=1
    } else {
      print $0
    }
  }' "$REPO_ROOT/dql_agent.py" > "$TRAIN_SCRIPT"

  # Build Python Attack enum list string like: Attack.CRUST_CRUSHER, Attack.OVEN_SPRING
  ATTACK_ENUMS=""
  for v in "${ATTACK_VALUES[@]}"; do
    name="${ATTACKS[$v]}"
    if [[ -z "$ATTACK_ENUMS" ]]; then
      ATTACK_ENUMS="Attack.$name"
    else
      ATTACK_ENUMS+=", Attack.$name"
    fi
  done

  # Prepare the replacement line for the random_loaf() creation.
  # Example: your_loaf = Loaf(flour=2, salt=3, sugar=1, attacks=[Attack.CRUST_CRUSHER, Attack.OVEN_SPRING])
  LOAF_CTOR_PY="    your_loaf = Loaf(flour=${FLOUR}, salt=${SALT}, sugar=${SUGAR}, attacks=[${ATTACK_ENUMS}])"

  # Replace the line that creates a random loaf with the explicit constructor.
  # Match a line containing 'your_loaf' and 'random_loaf('
  awk -v repl="$LOAF_CTOR_PY" 'BEGIN{replaced=0}
  {
    if(!replaced && $0 ~ /your_loaf[[:space:]]*=[[:space:]]*Loaf\.random_loaf\(\)/) {
      print repl
      replaced=1
    } else {
      print $0
    }
  }' "$TRAIN_SCRIPT" > "${TRAIN_SCRIPT}.tmp" && mv "${TRAIN_SCRIPT}.tmp" "$TRAIN_SCRIPT"

  chmod +x "$TRAIN_SCRIPT"
  echo "Created training script: $TRAIN_SCRIPT"
  echo "Train using: python \"$TRAIN_SCRIPT\""
fi

# Friendly next steps
cat <<EOT

Setup complete!

Loaf folder: $LOAF_DIR
 - loaf.json created at $LOAF_JSON_PATH
 - Streamlit module created at $MAIN_PY_PATH

Next steps (suggested):

1) Create a virtual environment and install required dependencies (example):
   python -m venv .venv
   # macOS / Linux:
   source .venv/bin/activate
   # Windows (PowerShell):
   # .venv\\Scripts\\Activate.ps1

   pip install torch streamlit tqdm

2) To train a model for your loaf (this generates <name>/model.pt):
   python "$REPO_ROOT/dql_agent_${LOAF_NAME}.py"

3) To run the arena UI using your loaf as player 1:
   streamlit run agent_arena.py "$LOAF_NAME/main.py"

   Or use the manual-play test interface:
   streamlit run test_interface.py

Notes / tips:
- The created module at $MAIN_PY_PATH will use a saved model if $LOAF_NAME/model.pt exists; otherwise the agent defaults to random actions so you can demo immediately.
- If you prefer not to train, run the UI and the loaf will be used with a random policy.
- The training script was created by copying the repo's dql_agent.py and replacing the name variable and the random-loaf line with a Loaf(...) that matches your inputs.

EOT

exit 0