from breadbrawl import Loaf
import json
from pathlib import Path
import random

# Auto-generated by setup_loaf.py
NAME = "PretrainedLoaf_36"

def _load_loaf():
    p = Path(__file__).resolve().parent / "loaf.json"
    with p.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return Loaf.deserialize(data)

your_loaf = _load_loaf()

# Lazy model loading: if model.pt exists and torch is available, a model will be used.
_model = None
try:
    import torch
    from dql_agent import DQNetwork
    model_path = Path("PretrainedLoafs/PretrainedLoaf_36") / "model.pt"
    if model_path.exists():
        _model = DQNetwork(your_loaf, 10, len(your_loaf.action_space))
        _model.load_state_dict(torch.load(model_path))
        _model.eval()
except Exception:
    _model = None

def loaf():
    return your_loaf

def agent(obs):
    # obs is the observation vector; fallback to random if no model or error
    if _model is None:
        return your_loaf.random_attack()
    try:
        return _model.select_action(obs)
    except Exception:
        return your_loaf.random_attack()
